include('shared.lua')
include('scripts/client/inventory.lua')
include('scripts/client/mainmenu.lua')
include('scripts/client/hud.lua')
include('scripts/client/hints.lua')
include('scripts/client/scoreboard.lua')
include('scripts/client/safemenu.lua')
include('scripts/client/shop.lua')
include('scripts/client/chat.lua')
include('scripts/client/backpack.lua')
include('scripts/client/character.lua')
include('scripts/client/trade.lua')
include('scripts/client/killtimer.lua')

include('scripts/shared/shar_items.lua')
include('scripts/shared/shar_shops.lua')
include('scripts/shared/shar_skills.lua')
include('scripts/shared/shar_pmodels.lua')
include('scripts/shared/shar_safezone.lua')
include('scripts/shared/shar_crafts.lua')

include('airdrop/client.lua')